export const FILES_ACTION_TYPES = {
    SET_APPROVERS: 'SET_APPROVERS',
    SET_CHOSEN_APPROVER: 'SET_CHOSEN_APPROVER',
    SET_DIRECTOR_ID: 'SET_DIRECTOR_ID',
    DELETE_CHOSEN_APPROVER: 'DELETE_CHOSEN_APPROVER',
    SET_CREATOR_CONTRACTS: 'SET_CREATOR_CONTRACTS',
    SET_APPROVER_CONTRACTS: 'SET_APPROVER_CONTRACTS',
};
